### PR TITLE
Fixed total amount bug <not showing NaN anymore>

### PR DESCRIPTION
**Pull request by Vishu-uut**
It was a easy fix you need to first access innertext of object then perform operations.

### CODE REVIEW

**Comment by samuel-ma** [comment]
Thanks alot @Vishu-uu 👌👊👊
Just finished merging in your solution
It'll take some time to see the changes in action
But your help is highly appreciated

**Comment by samuel-ma** [comment]
@Vishu-uut 
There wasn't any actual change on the code
The total still hasn't updated

**Comment by Vishu-uut** [comment]
> @Vishu-uut There wasn't any actual change on the code The total still hasn't updated

Are you sure the total is still showing NaN because it is working fine on my system?

**Comment by Vishu-uut** [comment]
Screenshot (5)
See It is working fine

**Comment by samuel-ma** [comment]
732 is not actually the total 
That's an HTML placeholder
The actual amount is supposed to increase each time the quantity increase when u press the plus button

**Pull request merged**
